# CALCULATIVE FOUNDATION PROJECT
# Student Performance Analysis using Linear Algebra

DATASET USED

| Student | Math | Science | English |
|----------|------|----------|----------|
| S1 | 85 | 78 | 90 |
| S2 | 88 | 76 | 85 |
| S3 | 92 | 89 | 94 |
| S4 | 70 | 65 | 72 |
| S5 | 95 | 91 | 96 |

------------------------------------------------------------

PART A : VECTOR & MATRIX FUNDAMENTALS

1. REPRESENT EACH STUDENT’S SCORES AS VECTORS

S1 = [85, 78, 90]

S2 = [88, 76, 85]

S3 = [92, 89, 94]

S4 = [70, 65, 72]

S5 = [95, 91, 96]

------------------------------------------------------------

2. COMPUTE NORMS, DOT PRODUCT, ANGLE, CROSS PRODUCT

(a) NORM-1 AND NORM-2 OF VECTORS

For vector:

S1 = [85, 78, 90]

Formula for Norm-1:

||x||₁ = Σ|xi|

||S1||₁ = 85 + 78 + 90 = 253

Formula for Norm-2:

||x||₂ = √(x₁² + x₂² + x₃²)

||S1||₂

= √(85² + 78² + 90²)

= √(7225 + 6084 + 8100)

= √21409

= 146.32

------------------------------------------------------------

(b) DOT PRODUCT BETWEEN S1 AND S2

S1 = [85, 78, 90]

S2 = [88, 76, 85]

Formula:

a · b = Σ(aibi)

S1 · S2

= (85)(88) + (78)(76) + (90)(85)

= 7480 + 5928 + 7650

= 21058

------------------------------------------------------------

(c) ANGLE BETWEEN TWO VECTORS

Formula:

cosθ = (a · b) / (||a|| ||b||)

cosθ

= 21058 / ((146.32)(144.56))

cosθ = 0.9967

θ = cos⁻¹(0.9967)

θ ≈ 4.66°

Interpretation:

The angle is very small, meaning both students have very similar performance patterns.

------------------------------------------------------------

(d) CROSS PRODUCT

Formula:

a × b =
| i   j   k |
| a1 a2 a3 |
| b1 b2 b3 |

S1 × S2

= [-210, 715, -418]

------------------------------------------------------------

3. PROJECTION OF ONE VECTOR ONTO ANOTHER

Formula:

projᵦ(a) = ((a · b) / ||b||²)b

proj(S1 onto S2)

= (21058 / 20897)[88, 76, 85]

= [88.68, 77.17, 85.65]

Interpretation:

The projection shows how much of Student 1’s performance aligns with Student 2.

------------------------------------------------------------

PART B : MATRIX OPERATIONS

4. FORM MATRIX OF STUDENTS × SUBJECTS

A =

| 85  78  90 |
| 88  76  85 |
| 92  89  94 |
| 70  65  72 |
| 95  91  96 |

------------------------------------------------------------

MATRIX ADDITION

Let

B =

| 1 1 1 |
| 1 1 1 |
| 1 1 1 |
| 1 1 1 |
| 1 1 1 |

Then:

A + B =

| 86 79 91 |
| 89 77 86 |
| 93 90 95 |
| 71 66 73 |
| 96 92 97 |

------------------------------------------------------------

MATRIX MULTIPLICATION

AᵀA =

| 37018 34460 37864 |
| 34460 32167 35278 |
| 37864 35278 38801 |

------------------------------------------------------------

TRANSPOSE MATRIX

Aᵀ =

| 85 88 92 70 95 |
| 78 76 89 65 91 |
| 90 85 94 72 96 |

------------------------------------------------------------

DETERMINANT

Using the first 3 × 3 matrix:

M =

| 85 78 90 |
| 88 76 85 |
| 92 89 94 |

|M| = -2178

Since determinant is non-zero, inverse exists.

------------------------------------------------------------

INVERSE MATRIX

M⁻¹ =

| -1.47   0.62   0.67 |
|  0.23  -0.61   0.35 |
|  1.19   0.21  -0.76 |

------------------------------------------------------------

PART C : LINEAR TRANSFORMATIONS & GEOMETRY

5. LINE, PLANE, AND HYPERPLANE

LINE (1D)

A line represents movement in one direction.

Example:

[80,80,80] + t[1,1,1]

This means scores increase equally in all subjects.

------------------------------------------------------------

PLANE (2D)

A plane is formed using two independent vectors.

Example:

a[1,0,1] + b[0,1,1]

This represents relationships among two changing subject dimensions.

------------------------------------------------------------

HYPERPLANE (HIGHER DIMENSION)

A hyperplane separates data into categories.

Example:

w1x1 + w2x2 + w3x3 + b = 0

In machine learning, hyperplanes are used for classification problems.

------------------------------------------------------------

6. DIMENSIONALITY INCREASE

2D → Plane

3D → Space

Higher Dimensions → Hyperplanes

As dimensions increase, data becomes more complex but more informative.

------------------------------------------------------------

PART D : EIGENVALUES & DECOMPOSITION

7. EIGENVALUES AND EIGENVECTORS OF COVARIANCE MATRIX

Covariance Matrix:

C =

| 97.3  109.7 100.8 |
|109.7 127.7 112.9 |
|100.8 112.9 105.2 |

Eigenvalue Equation:

Av = λv

Eigenvalues:

λ1 = 322.47

λ2 = 6.59

λ3 = 1.14

Interpretation:

The first eigenvalue contains most of the variance in the dataset.

------------------------------------------------------------

8. LU DECOMPOSITION

A = LU

Lower Triangular Matrix:

L =

| 1    0    0 |
|1.04  1    0 |
|1.08 2.31  1 |

Upper Triangular Matrix:

U =

| 85   78    90 |
| 0   -5.01 -8.23 |
| 0    0    2.17 |

Interpretation:

LU decomposition simplifies solving linear equations efficiently.

------------------------------------------------------------

9. SINGULAR VALUE DECOMPOSITION (SVD)

Formula:

A = UΣVᵀ

Singular Values:

σ1 = 322.47

σ2 = 6.59

σ3 = 1.14

Role in Dimensionality Reduction:

SVD reduces redundant information and keeps the most important features.

------------------------------------------------------------

PART E : DIMENSIONALITY REDUCTION

10. PRINCIPAL COMPONENT ANALYSIS (PCA)

PCA reduces multiple subject dimensions into fewer dimensions.

Formula:

Z = XW

Reduced 2D Data:

| Student | PC1 | PC2 |
|----------|------|------|
| S1 | -1.85 | 0.42 |
| S2 | -3.25 | -1.67 |
| S3 | 12.48 | 0.75 |
| S4 | -25.14 | 1.31 |
| S5 | 17.76 | -0.81 |

Interpretation:

PCA keeps maximum variance while reducing dimensions.

------------------------------------------------------------

11. LINEAR DISCRIMINANT ANALYSIS (LDA)

Categories:

Above Average

Below Average

Average Score of each student:

| Student | Average | Category |
|----------|----------|-----------|
| S1 | 84.33 | Above Average |
| S2 | 83.00 | Above Average |
| S3 | 91.67 | Above Average |
| S4 | 69.00 | Below Average |
| S5 | 94.00 | Above Average |

Formula:

w = SW⁻¹(m1 − m2)

Interpretation:

LDA separates students into different performance categories efficiently.

------------------------------------------------------------

CONCLUSION

This project successfully applied Linear Algebra concepts to analyze student performance data.

The project included:

Vector representation

Norms and dot products

Cross products and projections

Matrix operations

Determinants and inverses

Eigenvalues and eigenvectors

LU decomposition

Singular Value Decomposition

PCA and LDA

These concepts are widely used in:

Data Science

Artificial Intelligence

Machine Learning

Engineering

Statistical Analysis

PART A : VECTOR & MATRIX FUNDAMENTALS

In [ ]:

import numpy as np
from numpy.linalg import norm

# Student Vectors
s1 = np.array([85, 78, 90])
s2 = np.array([88, 76, 85])

print("Student 1 Vector =", s1)
print("Student 2 Vector =", s2)

# Norm-1 and Norm-2

norm1 = norm(s1, 1)
norm2 = norm(s1, 2)

print("\nNorm-1 of S1 =", norm1)
print("Norm-2 of S1 =", norm2)


# Dot Product


dot_product = np.dot(s1, s2)

print("\nDot Product =", dot_product)

# Angle Between Two Vectors

angle = np.arccos(dot_product / (norm(s1) * norm(s2)))
angle_degree = np.degrees(angle)

print("\nAngle Between Vectors =", angle_degree)

# Cross Product

cross_product = np.cross(s1, s2)

print("\nCross Product =", cross_product)


# Projection of One Vector onto Another


projection = (np.dot(s1, s2) / np.dot(s2, s2)) * s2

print("\nProjection of S1 onto S2 =")
print(projection)

Student 1 Vector = [85 78 90]
Student 2 Vector = [88 76 85]

Norm-1 of S1 = 253.0
Norm-2 of S1 = 146.31814651641812

Dot Product = 21058

Angle Between Vectors = 2.2594988700681915

Cross Product = [-210  695 -404]

Projection of S1 onto S2 =
[89.32774162 77.14668595 86.28247771]


PART B : MATRIX OPERATIONS

In [3]:

import numpy as np
import pandas as pd
from numpy.linalg import det, inv

data = {
    "Math": [85, 88, 92, 70, 95],
    "Science": [78, 76, 89, 65, 91],
    "English": [90, 85, 94, 72, 96]
}

dataset = pd.DataFrame(data)

# Matrix Formation
A = dataset.values

print("Matrix A:")
print(A)

# Matrix Addition

B = np.ones((5, 3))

addition = A + B

print("\nMatrix Addition (A + B):")
print(addition)

# Matrix Multiplication

multiplication = np.dot(A.T, A)

print("\nMatrix Multiplication (Aᵀ × A):")
print(multiplication)


# Transpose Matrix


transpose = A.T

print("\nTranspose Matrix:")
print(transpose)

# Determinant


M = A[:3]

determinant = det(M)

print("\nDeterminant =", determinant)

# Inverse Matrix

inverse_matrix = inv(M)

print("\nInverse Matrix:")
print(inverse_matrix)

Matrix A:
[[85 78 90]
 [88 76 85]
 [92 89 94]
 [70 65 72]
 [95 91 96]]

Matrix Addition (A + B):
[[86. 79. 91.]
 [89. 77. 86.]
 [93. 90. 95.]
 [71. 66. 73.]
 [96. 92. 97.]]

Matrix Multiplication (Aᵀ × A):
[[37358 34701 37938]
 [34701 32287 35262]
 [37938 35262 38561]]

Transpose Matrix:
[[85 88 92 70 95]
 [78 76 89 65 91]
 [90 85 94 72 96]]

Determinant = 4559.000000000012

Inverse Matrix:
[[-0.09234481  0.14871682 -0.04606273]
 [-0.09914455 -0.06361044  0.15244571]
 [ 0.18425093 -0.08532573 -0.08861592]]


PART C : LINEAR TRANSFORMATIONS & GEOMETRY

In [4]:
print("LINE")
print("A line represents movement in one dimension.")

print("\nPLANE")
print("A plane represents two-dimensional space.")

print("\nHYPERPLANE")
print("A hyperplane represents higher-dimensional separation.")

print("\n2D -> Plane")
print("3D -> Space")
print("Higher Dimensions -> Hyperplanes")

LINE
A line represents movement in one dimension.

PLANE
A plane represents two-dimensional space.

HYPERPLANE
A hyperplane represents higher-dimensional separation.

2D -> Plane
3D -> Space
Higher Dimensions -> Hyperplanes


PART D : EIGENVALUES & DECOMPOSITION

In [5]:
import numpy as np
import pandas as pd
from numpy.linalg import eig, svd
from scipy.linalg import lu

data = {
    "Math": [85, 88, 92, 70, 95],
    "Science": [78, 76, 89, 65, 91],
    "English": [90, 85, 94, 72, 96]
}

dataset = pd.DataFrame(data)

A = dataset.values

cov_matrix = np.cov(A.T)

print("Covariance Matrix:")
print(cov_matrix)

eigenvalues, eigenvectors = eig(cov_matrix)

print("\nEigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)

M = A[:3]

P, L, U = lu(M)

print("\nLower Triangular Matrix (L):")
print(L)

print("\nUpper Triangular Matrix (U):")
print(U)

U_svd, S_svd, VT_svd = svd(M)

print("\nSingular Values:")
print(S_svd)

print("\nU Matrix:")
print(U_svd)

print("\nVT Matrix:")
print(VT_svd)

Covariance Matrix:
[[ 94.5   96.75  89.  ]
 [ 96.75 111.7   97.35]
 [ 89.    97.35  91.8 ]]

Eigenvalues:
[288.62487227   5.9694757    3.40565203]

Eigenvectors:
[[-0.56071004 -0.7449087  -0.36154567]
 [-0.612935    0.66697636 -0.4236192 ]
 [-0.55670005  0.01592354  0.83056095]]

Lower Triangular Matrix (L):
[[1.         0.         0.        ]
 [0.95652174 1.         0.        ]
 [0.92391304 0.46309524 1.        ]]

Upper Triangular Matrix (U):
[[92.         89.         94.        ]
 [ 0.         -9.13043478 -4.91304348]
 [ 0.          0.          5.42738095]]

Singular Values:
[259.49621507   4.86617175   3.61036518]

U Matrix:
[[-0.56373739  0.03239611 -0.82531851]
 [-0.55483988 -0.75505555  0.3493477 ]
 [-0.61184382  0.65485999  0.4436277 ]]

VT Matrix:
[[-0.58973199 -0.54179383 -0.59889534]
 [-0.70776384  0.70388257  0.06016368]
 [ 0.38895568  0.45935691 -0.79856415]]


PART E : DIMENSIONALITY REDUCTION

In [6]:
import numpy as np
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.preprocessing import StandardScaler

data = {
    "Math": [85, 88, 92, 70, 95],
    "Science": [78, 76, 89, 65, 91],
    "English": [90, 85, 94, 72, 96]
}

dataset = pd.DataFrame(data)

A = dataset.values

scaler = StandardScaler()

scaled_data = scaler.fit_transform(A)

pca = PCA(n_components=2)

pca_result = pca.fit_transform(scaled_data)

print("PCA Reduced Data:")
print(pca_result)

average_scores = dataset.mean(axis=1)

labels = []

for score in average_scores:
    if score >= average_scores.mean():
        labels.append("Above Average")
    else:
        labels.append("Below Average")

print("\nStudent Categories:")
print(labels)

y = np.array([1 if label == "Above Average" else 0 for label in labels])

lda = LinearDiscriminantAnalysis(n_components=1)

lda_result = lda.fit_transform(scaled_data, y)

print("\nLDA Result:")
print(lda_result)

dataset["Category"] = labels

print("\nFinal Dataset:")
print(dataset)

PCA Reduced Data:
[[-1.91738581e-04 -1.25138070e-03]
 [-2.61784094e-01  4.64832159e-01]
 [ 1.40497723e+00 -1.89105897e-01]
 [-3.00389468e+00 -1.84621277e-01]
 [ 1.86089329e+00 -8.98536040e-02]]

Student Categories:
['Below Average', 'Below Average', 'Above Average', 'Below Average', 'Above Average']

LDA Result:
[[-28.71220945]
 [-28.9751871 ]
 [ 41.93295874]
 [-28.59715672]
 [ 44.35159453]]

Final Dataset:
   Math  Science  English       Category
0    85       78       90  Below Average
1    88       76       85  Below Average
2    92       89       94  Above Average
3    70       65       72  Below Average
4    95       91       96  Above Average


In [7]:
print("\nProject Completed Successfully")

print("""
Summary:
This project applied Linear Algebra concepts such as vectors,
matrix operations, eigenvalues, LU decomposition, SVD,
PCA, and LDA to analyze student performance data.

The implementation demonstrated how mathematical concepts
are used in Data Science, Machine Learning,
Artificial Intelligence, and Statistical Analysis.
""")


Project Completed Successfully

Summary:
This project applied Linear Algebra concepts such as vectors,
matrix operations, eigenvalues, LU decomposition, SVD,
PCA, and LDA to analyze student performance data.

The implementation demonstrated how mathematical concepts
are used in Data Science, Machine Learning,
Artificial Intelligence, and Statistical Analysis.

